apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user-request-dev01
spec:
  request: 
  expirationSeconds: 86400
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
