
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rbac-ns
  name: sa-demo
spec:
  selector:
    matchLabels:
      run: sa-demo
  replicas: 1
  template:
    metadata:
      labels:
        run: sa-demo
    spec:
      serviceAccountName: my-sa
      containers:
      - name: sa-demo
        image: tasb/nginx-kubectl
