apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-deploy
spec:
  selector:
    matchLabels:
      app: node-affinity
  replicas: 6
  template:
    metadata:
      labels:
        app: node-affinity
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64 
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - "ssd"
                - "nvme"
          - weight: 10
            preference:
              matchExpressions:
              - key: parity
                operator: In
                values:
                - "true"
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 300m