apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: podinfo-ds
  namespace: ds-ns
spec:
  selector:
    matchLabels:
        target: info-pod
  template:
    metadata:
      name: podinfo
      labels:
        target: info-pod
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo
        ports:
        - containerPort: 80
          protocol: TCP
